apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: testapp
    k8s-app: testapp
  name: testapp
  namespace: testapp
spec:
  endpoints:
  - path: /metrics
  - interval: 30s
    port: http
    scheme: http
  selector:
    matchLabels:
      app: testapp
